import { KeywordItem } from './autocomplete';

export interface ContentBrief {
  title: string;
  seed: string;
  recommendedH1: string;
  recommendedH2s: string[];
  faqSection: { question: string; targetKeyword: string }[];
  primaryKeywords: string[];
  secondaryKeywords: string[];
  markdown: string;
}

/**
 * Transforms an autocomplete query into a natural, authoritative People Also Ask (PAA) style question.
 */
export function formatPaaQuestion(keyword: string): string {
  const clean = keyword.trim();
  const lower = clean.toLowerCase();

  // 1. Explicit question keywords (how, what, why, can, is, are, which, where, does, do, should, will, who)
  if (/^(how|what|why|can|is|are|which|where|does|do|should|will|who)\b/i.test(lower)) {
    const capitalized = clean.charAt(0).toUpperCase() + clean.slice(1);
    return capitalized.endsWith('?') ? capitalized : `${capitalized}?`;
  }

  // 2. Comparison queries
  if (/\b(vs|versus|difference between)\b/i.test(lower)) {
    return `What is the difference between ${clean}?`;
  }

  // 3. Pricing / Cost queries
  if (/\b(free|cost|price|pricing|cheap)\b/i.test(lower)) {
    return `Is there a free version of ${clean.replace(/\b(free|cost|price|pricing|cheap)\b/gi, '').trim()}?`;
  }

  // 4. Best / Top queries
  if (/\b(best|top|review|reviews)\b/i.test(lower)) {
    const topic = clean.replace(/\b(best|top|review|reviews)\b/gi, '').trim();
    return `What is the best ${topic || clean}?`;
  }

  // 5. Default natural question phrasing for noun phrases
  return `What is ${clean} and how does it work?`;
}

export function generateContentBrief(seed: string, keywords: KeywordItem[]): ContentBrief {
  const topKeywords = [...keywords].sort((a, b) => b.relativeScore - a.relativeScore);
  const primary = topKeywords.slice(0, 5).map((k) => k.keyword);
  const secondary = topKeywords.slice(5, 20).map((k) => k.keyword);

  // 1. Extract genuine question-based autocomplete queries (Questions category & prefix matches)
  const explicitQuestions = topKeywords.filter((k) =>
    /^(how|what|why|where|when|who|which|can|is|are|does|do)\b/i.test(k.keyword) ||
    k.sources.some((s) => s.startsWith('question-'))
  );

  const fallbackQuestions = topKeywords.filter((k) => k.intent === 'informational');
  const selectedFaqKeywords = Array.from(
    new Set([...explicitQuestions, ...fallbackQuestions])
  ).slice(0, 6);

  // 2. Extract commercial and review keywords for H2 subheadings
  const commercialKeywords = topKeywords.filter((k) =>
    /(best|top|vs|guide|tips|how to|review|alternative|generator|creator)/i.test(k.keyword)
  );

  const cleanSeedTitle = seed.charAt(0).toUpperCase() + seed.slice(1);
  const recommendedH1 = `The Complete Guide to ${cleanSeedTitle}: Best Practices & Strategies`;

  const recommendedH2s = [
    `What is ${cleanSeedTitle}? (Overview & Fundamentals)`,
    ...commercialKeywords.slice(0, 5).map((k) => `## ${k.keyword.charAt(0).toUpperCase() + k.keyword.slice(1)}`),
    `Key Benefits & Best Practices for ${cleanSeedTitle}`,
    `Frequently Asked Questions About ${cleanSeedTitle}`,
  ];

  const faqList = selectedFaqKeywords.map((k) => ({
    question: formatPaaQuestion(k.keyword),
    targetKeyword: k.keyword,
  }));

  const markdown = `# SEO Content Brief: ${cleanSeedTitle}

## 🎯 Target Overview
- **Primary Seed Query**: \`${seed}\`
- **Recommended H1**: ${recommendedH1}
- **Target Audience Intent**: Informational & Commercial

---

## 🔑 Keyword Targets
### Primary Focus Keywords (Top Relative Score)
${primary.map((k) => `- **${k}**`).join('\n')}

### Secondary & Long-Tail Keywords
${secondary.map((k) => `- ${k}`).join('\n')}

---

## 📑 Proposed Article Structure
${recommendedH2s.map((h2, i) => `### Section [${i + 1}]: ${h2}\n*Notes: Target relevant sub-queries and provide actionable examples.*`).join('\n\n')}

---

## ❓ People Also Ask & Recommended FAQs (Google FAQ Schema Ready)
${faqList.map((f) => `### Q: ${f.question}\n**Targeting Query**: \`${f.targetKeyword}\`\n*Answer guidance: Provide a direct, concise 2-sentence answer for Google Featured Snippets.*`).join('\n\n')}

---
*Generated by Google Keyword Dominator (GKD) Autocomplete Intelligence*
`;

  return {
    title: `SEO Brief: ${cleanSeedTitle}`,
    seed,
    recommendedH1,
    recommendedH2s,
    faqSection: faqList,
    primaryKeywords: primary,
    secondaryKeywords: secondary,
    markdown,
  };
}
