import { KeywordItem } from './autocomplete';

export interface ContentBrief {
  title: string;
  seed: string;
  recommendedH1: string;
  recommendedH2s: string[];
  faqSection: { question: string; targetKeyword: string }[];
  primaryKeywords: string[];
  secondaryKeywords: string[];
  markdown: string;
}

export function generateContentBrief(seed: string, keywords: KeywordItem[]): ContentBrief {
  const topKeywords = [...keywords].sort((a, b) => b.relativeScore - a.relativeScore);
  const primary = topKeywords.slice(0, 5).map((k) => k.keyword);
  const secondary = topKeywords.slice(5, 20).map((k) => k.keyword);

  // Extract question-based keywords for FAQ
  const questionKeywords = topKeywords.filter((k) =>
    /^(how|what|why|where|when|who|which|can|is|are)/i.test(k.keyword) ||
    k.sources.some((s) => s.startsWith('question-'))
  );

  // Extract commercial / comparison keywords for H2s
  const commercialKeywords = topKeywords.filter((k) =>
    /(best|top|vs|guide|tips|how to|review)/i.test(k.keyword)
  );

  const recommendedH1 = `The Ultimate Guide to ${seed.replace(/\b\w/g, (c) => c.toUpperCase())}: Everything You Need to Know`;

  const recommendedH2s = [
    `What is ${seed}? (Overview & Fundamentals)`,
    ...commercialKeywords.slice(0, 4).map((k) => k.keyword.replace(/\b\w/g, (c) => c.toUpperCase())),
    `Key Benefits & Best Practices for ${seed}`,
    `Frequently Asked Questions About ${seed}`,
  ];

  const faqList = (questionKeywords.length > 0 ? questionKeywords.slice(0, 5) : topKeywords.slice(0, 4)).map((k) => ({
    question: k.keyword.endsWith('?') ? k.keyword : `${k.keyword.replace(/\b\w/g, (c) => c.toUpperCase())}?`,
    targetKeyword: k.keyword,
  }));

  const markdown = `# SEO Content Brief: ${seed}

## 🎯 Target Overview
- **Primary Seed Query**: ${seed}
- **Recommended H1**: ${recommendedH1}
- **Target Audience Intent**: Informational & Commercial

---

## 🔑 Keyword Targets
### Primary Focus Keywords (Top Relative Score)
${primary.map((k) => `- **${k}**`).join('\n')}

### Secondary & Long-Tail Keywords
${secondary.map((k) => `- ${k}`).join('\n')}

---

## 📑 Proposed Article Structure

${recommendedH2s.map((h2, i) => `### H2 [${i + 1}]: ${h2}\n*Notes: Target relevant sub-queries and provide actionable examples.*`).join('\n\n')}

---

## ❓ Recommended FAQ Section (Schema Markup Ready)
${faqList.map((f) => `### Q: ${f.question}\n**Target Keyword**: \`${f.targetKeyword}\`\n*Answer guidance: Provide a direct, concise 2-sentence answer for Google Featured Snippets.*`).join('\n\n')}

---
*Generated by Google Keyword Dominator • 100% Genuine Google Autocomplete Search Data*
`;

  return {
    title: `SEO Brief: ${seed}`,
    seed,
    recommendedH1,
    recommendedH2s,
    faqSection: faqList,
    primaryKeywords: primary,
    secondaryKeywords: secondary,
    markdown,
  };
}
