import { KeywordItem } from './autocomplete';

export interface ContentBrief {
  seed: string;
  recommendedH2s: string[];
  faqSection: { question: string; targetKeyword: string }[];
  primaryKeywords: string[];
  secondaryKeywords: string[];
  markdown: string;
}

export function generateContentBrief(seed: string, keywords: KeywordItem[]): ContentBrief {
  const topKeywords = [...keywords].sort((a, b) => b.relativeScore - a.relativeScore);
  const primary = topKeywords.slice(0, 5).map((k) => k.keyword);
  const secondary = topKeywords.slice(5, 20).map((k) => k.keyword);

  // STRICT 100% REAL AUTOCOMPLETE QUESTIONS ONLY
  const questionKeywords = topKeywords.filter((k) =>
    /^(how|what|why|where|when|who|which|can|is|are|does|do|should|will)\b/i.test(k.keyword) ||
    k.sources.some((s) => s.startsWith('question-'))
  ).slice(0, 6);

  // 100% REAL COMMERCIAL & COMPARISON QUERIES
  const commercialKeywords = topKeywords.filter((k) =>
    k.intent === 'commercial' || k.intent === 'transactional' || /(best|top|vs|guide|tips|how to|review|alternative|generator|creator)/i.test(k.keyword)
  ).slice(0, 6);

  const recommendedH2s = commercialKeywords.map((k) => `## ${k.keyword}`);

  const faqList = questionKeywords.map((k) => ({
    question: k.keyword,
    targetKeyword: k.keyword,
  }));

  const markdown = `# Content Brief: ${seed}

## Target Seed
- **Seed Keyword:** \`${seed}\`

## Primary Keywords to Include
${primary.map((k) => `- [ ] ${k}`).join('\n')}

## Secondary & Long-Tail Keywords
${secondary.map((k) => `- ${k}`).join('\n')}

## Recommended H2 Subheadings (Real Google Search Queries)
${recommendedH2s.join('\n')}

${faqList.length > 0 ? `## Recommended FAQs (Real Google Question Queries)
${faqList.map((f) => `### Q: ${f.question}\n- *Target Query:* \`${f.targetKeyword}\``).join('\n\n')}` : ''}

---
*Generated by Google Keyword Dominator (GKD) • 100% Real Autocomplete Data*
`;

  return {
    seed,
    recommendedH2s,
    faqSection: faqList,
    primaryKeywords: primary,
    secondaryKeywords: secondary,
    markdown,
  };
}
