'use client';

import React, { useState } from 'react';
import { KeywordItem } from '@/lib/autocomplete';
import { X, Copy, Check, FileText, Sparkles, HelpCircle, Layers, Gauge } from 'lucide-react';
import { PageGraderDrawer } from './PageGraderDrawer';

interface ContentBriefModalProps {
  seed: string;
  keywords: KeywordItem[];
  isOpen: boolean;
  onClose: () => void;
}

export const ContentBriefModal: React.FC<ContentBriefModalProps> = ({
  seed,
  keywords,
  isOpen,
  onClose,
}) => {
  const [copied, setCopied] = useState(false);
  const [isGraderOpen, setIsGraderOpen] = useState(false);

  if (!isOpen) return null;

  // Filter top keywords by intent for the brief
  const primaryKeywords = keywords.slice(0, 5);

  // STRICT 100% REAL AUTOCOMPLETE QUESTIONS ONLY:
  // Must match real question prefixes from Google Autocomplete or question-* sources.
  // Zero synthetic text, zero template prefixes added.
  const questionKeywords = keywords.filter((k) =>
    /^(how|what|why|can|is|are|which|where|does|do|should|will|who)\b/i.test(k.keyword) ||
    k.sources.some((s) => s.startsWith('question-'))
  ).slice(0, 6);

  const commercialKeywords = keywords.filter((k) =>
    k.intent === 'commercial' || k.intent === 'transactional' || /(best|top|vs|guide|tips|how to|review|alternative|generator|creator)/i.test(k.keyword)
  ).slice(0, 6);

  const cleanSeedTitle = seed.charAt(0).toUpperCase() + seed.slice(1);

  const brief = {
    title: `Complete Guide to ${cleanSeedTitle}: Best Practices & Strategies`,
    targetSeed: seed,
    totalKeywordsDiscovered: keywords.length,
    coreChecklist: primaryKeywords.map((k) => k.keyword),
    secondaryTopics: commercialKeywords.map((k) => k.keyword),
    faqSection: questionKeywords.map((k) => {
      const q = k.keyword.trim();
      const formatted = q.charAt(0).toUpperCase() + q.slice(1);
      return {
        question: formatted.endsWith('?') ? formatted : `${formatted}?`,
        targetKeyword: k.keyword,
      };
    }),
  };

  const markdownContent = `# Content Brief: ${brief.title}

## Target Core Seed
- **Seed Keyword:** \`${brief.targetSeed}\`
- **Total Discovered Long-Tail Queries:** ${brief.totalKeywordsDiscovered}

## Target Checklist (Must Include)
${brief.coreChecklist.map((kw) => `- [ ] ${kw}`).join('\n')}

## Recommended H2 Subheadings
${brief.secondaryTopics.map((kw) => `- ## ${kw.charAt(0).toUpperCase() + kw.slice(1)}`).join('\n')}

${brief.faqSection.length > 0 ? `## Recommended FAQs (Google Autocomplete Questions)
${brief.faqSection.map((faq) => `### Q: ${faq.question}\n- *Target Query:* \`${faq.targetKeyword}\``).join('\n\n')}` : ''}

---
*Generated by Google Keyword Dominator (GKD) • 100% Real Autocomplete Data*
`;

  const handleCopyMarkdown = async () => {
    await navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <>
      <div className="fixed inset-0 z-50 bg-slate-950/70 backdrop-blur-xs flex items-center justify-center p-4 overflow-y-auto animate-fadeIn">
        <div className="bg-white rounded-2xl max-w-2xl w-full shadow-2xl border border-slate-200 overflow-hidden flex flex-col max-h-[90vh]">
          {/* Modal Header */}
          <div className="p-4 sm:p-6 border-b border-slate-100 flex items-center justify-between bg-gradient-to-r from-blue-50 to-indigo-50">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-blue-600 text-white rounded-xl shadow-md shadow-blue-500/20">
                <FileText className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
                  1-Click SEO Content Brief
                  <span className="text-[10px] bg-blue-100 text-blue-800 font-extrabold px-2 py-0.5 rounded-full">
                    Ready to Write
                  </span>
                </h3>
                <p className="text-xs text-slate-500">
                  Target Seed: <strong className="text-slate-800 font-semibold">{seed || 'Seed Topic'}</strong>
                </p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-2 text-slate-400 hover:text-slate-700 hover:bg-white rounded-lg transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Modal Body */}
          <div className="p-4 sm:p-6 overflow-y-auto space-y-6 flex-1 text-sm">
            {/* Suggested Title */}
            <div className="space-y-1.5 p-3.5 bg-blue-50/50 rounded-xl border border-blue-100">
              <span className="text-xs font-bold uppercase tracking-wider text-blue-700 block flex items-center gap-1">
                <Sparkles className="w-3.5 h-3.5" />
                Suggested Article H1 Title
              </span>
              <div className="font-extrabold text-slate-900 text-base">{brief.title}</div>
            </div>

            {/* Core Checklist */}
            <div className="space-y-2">
              <span className="text-xs font-bold uppercase tracking-wider text-slate-500 block flex items-center gap-1">
                <Layers className="w-3.5 h-3.5" />
                Primary Keywords to Include
              </span>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {brief.coreChecklist.map((kw, i) => (
                  <div key={i} className="flex items-center gap-2 p-2 bg-slate-50 rounded-lg border border-slate-200 text-xs font-semibold text-slate-700">
                    <span className="w-2 h-2 rounded-full bg-blue-500 shrink-0" />
                    <span className="truncate">{kw}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Secondary Subheadings */}
            <div className="space-y-2">
              <span className="text-xs font-bold uppercase tracking-wider text-slate-500 block">
                Recommended H2 Subheadings
              </span>
              <div className="space-y-1.5">
                {brief.secondaryTopics.map((kw, i) => (
                  <div key={i} className="p-2 bg-slate-50 rounded-lg border border-slate-200 text-xs text-slate-800">
                    ## <strong className="capitalize">{kw}</strong>
                  </div>
                ))}
              </div>
            </div>

            {/* FAQ Questions */}
            {brief.faqSection.length > 0 && (
              <div className="space-y-3">
                <span className="text-xs font-bold uppercase tracking-wider text-slate-500 block flex items-center gap-1">
                  <HelpCircle className="w-3.5 h-3.5" />
                  Recommended FAQs (Real Google Questions)
                </span>
                <div className="space-y-2">
                  {brief.faqSection.map((faq, i) => (
                    <div key={i} className="p-3 bg-slate-50 rounded-xl border border-slate-200 space-y-1 text-xs">
                      <div className="font-bold text-slate-900 flex items-start gap-1.5">
                        <span className="text-blue-600 font-black">Q:</span>
                        <span>{faq.question}</span>
                      </div>
                      <div className="text-[11px] text-slate-500 pl-4">
                        Target query: <code className="bg-slate-200 px-1 py-0.5 rounded text-slate-800">{faq.targetKeyword}</code>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Modal Footer */}
          <div className="p-4 bg-slate-50 border-t border-slate-100 flex items-center justify-between">
            <button
              onClick={() => setIsGraderOpen(true)}
              className="px-3.5 py-2 bg-indigo-50 hover:bg-indigo-100 text-indigo-700 border border-indigo-200 rounded-xl text-xs font-bold flex items-center gap-1.5 transition-colors cursor-pointer"
            >
              <Gauge className="w-4 h-4 text-indigo-600" />
              <span>Grade Live Page (0-100 SEO)</span>
            </button>

            <div className="flex items-center gap-2">
              <button
                onClick={onClose}
                className="px-4 py-2 bg-white border border-slate-300 hover:bg-slate-100 text-slate-700 rounded-xl text-xs font-bold cursor-pointer transition-colors"
              >
                Close
              </button>
              <button
                onClick={handleCopyMarkdown}
                className="px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-xs font-bold flex items-center gap-1.5 shadow-md cursor-pointer transition-colors"
              >
                {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
                <span>{copied ? 'Copied Brief' : 'Copy Markdown'}</span>
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* 1-Click Page Grader Drawer */}
      <PageGraderDrawer
        isOpen={isGraderOpen}
        onClose={() => setIsGraderOpen(false)}
        targetKeyword={seed}
      />
    </>
  );
};
