'use client';

import React, { useState } from 'react';
import { KeywordItem } from '@/lib/autocomplete';
import { X, Copy, Check, FileText, Sparkles, HelpCircle, Layers, Gauge } from 'lucide-react';
import { PageGraderDrawer } from './PageGraderDrawer';

interface ContentBriefModalProps {
  seed: string;
  keywords: KeywordItem[];
  isOpen: boolean;
  onClose: () => void;
}

export const ContentBriefModal: React.FC<ContentBriefModalProps> = ({
  seed,
  keywords,
  isOpen,
  onClose,
}) => {
  const [copied, setCopied] = useState(false);
  const [isGraderOpen, setIsGraderOpen] = useState(false);

  if (!isOpen) return null;

  // Filter top keywords by intent for the brief
  const primaryKeywords = keywords.slice(0, 5);
  const questions = keywords.filter((k) => k.intent === 'informational').slice(0, 6);
  const commercialKeywords = keywords.filter((k) => k.intent === 'commercial' || k.intent === 'transactional').slice(0, 6);

  const brief = {
    title: `Complete Guide to ${seed.charAt(0).toUpperCase() + seed.slice(1)}: Best Practices & Strategies`,
    targetSeed: seed,
    totalKeywordsDiscovered: keywords.length,
    coreChecklist: primaryKeywords.map((k) => k.keyword),
    secondaryTopics: commercialKeywords.map((k) => k.keyword),
    faqSection: questions.map((k) => ({
      question: k.keyword.charAt(0).toUpperCase() + k.keyword.slice(1) + '?',
      targetKeyword: k.keyword,
    })),
  };

  const markdownContent = `# Content Brief: ${brief.title}

## Target Core Seed
- **Seed Keyword:** \`${brief.targetSeed}\`
- **Total Discovered Long-Tail Queries:** ${brief.totalKeywordsDiscovered}

## Target Checklist (Must Include)
${brief.coreChecklist.map((kw) => `- [ ] ${kw}`).join('\n')}

## Recommended H2 Subheadings & Commercial Variants
${brief.secondaryTopics.map((kw) => `- ## ${kw.charAt(0).toUpperCase() + kw.slice(1)}`).join('\n')}

## Suggested FAQ Section (Google FAQ Schema Ready)
${brief.faqSection.map((faq) => `### Q: ${faq.question}\n- *Targeting:* \`${faq.targetKeyword}\``).join('\n\n')}

---
*Generated by Google Keyword Dominator (GKD) Autocomplete Intelligence*
`;

  const handleCopyMarkdown = async () => {
    await navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <>
      <div className="fixed inset-0 z-50 bg-slate-950/70 backdrop-blur-xs flex items-center justify-center p-4 overflow-y-auto animate-fadeIn">
        <div className="bg-white rounded-2xl max-w-2xl w-full shadow-2xl border border-slate-200 overflow-hidden flex flex-col max-h-[90vh]">
          {/* Modal Header */}
          <div className="p-4 sm:p-6 border-b border-slate-100 flex items-center justify-between bg-gradient-to-r from-blue-50 to-indigo-50">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-blue-600 text-white rounded-xl shadow-md shadow-blue-500/20">
                <FileText className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
                  1-Click SEO Content Brief
                  <span className="text-[10px] bg-blue-100 text-blue-800 font-extrabold px-2 py-0.5 rounded-full">
                    Ready to Write
                  </span>
                </h3>
                <p className="text-xs text-slate-500">
                  Target Seed: <strong className="text-slate-800 font-semibold">{seed || 'Seed Topic'}</strong>
                </p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-2 text-slate-400 hover:text-slate-700 hover:bg-white rounded-lg transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Modal Body */}
          <div className="p-4 sm:p-6 overflow-y-auto space-y-6 flex-1 text-sm">
            {/* Suggested Title */}
            <div className="space-y-1.5 p-3.5 bg-blue-50/50 rounded-xl border border-blue-100">
              <span className="text-xs font-bold uppercase tracking-wider text-blue-700 block flex items-center gap-1">
                <Sparkles className="w-3.5 h-3.5" />
                Suggested Article H1 Title
              </span>
              <div className="font-extrabold text-slate-900 text-base">{brief.title}</div>
            </div>

            {/* Core Checklist */}
            <div className="space-y-2">
              <span className="text-xs font-bold uppercase tracking-wider text-slate-500 block flex items-center gap-1">
                <Layers className="w-3.5 h-3.5" />
                Primary Keywords to Include
              </span>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {brief.coreChecklist.map((kw, i) => (
                  <div key={i} className="flex items-center gap-2 p-2 bg-slate-50 rounded-lg border border-slate-200 text-xs font-semibold text-slate-700">
                    <span className="w-2 h-2 rounded-full bg-blue-500 shrink-0" />
                    <span className="truncate">{kw}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Secondary Subheadings */}
            <div className="space-y-2">
              <span className="text-xs font-bold uppercase tracking-wider text-slate-500 block">
                Recommended H2 Subheadings
              </span>
              <div className="space-y-1.5">
                {brief.secondaryTopics.map((kw, i) => (
                  <div key={i} className="p-2 bg-slate-50 rounded-lg border border-slate-200 text-xs text-slate-800">
                    ## <strong className="capitalize">{kw}</strong>
                  </div>
                ))}
              </div>
            </div>

            {/* FAQ Questions */}
            <div className="space-y-3">
              <span className="text-xs font-bold uppercase tracking-wider text-slate-500 block flex items-center gap-1">
                <HelpCircle className="w-3.5 h-3.5" />
                Recommended FAQs (Schema Markup Ready)
              </span>
              <div className="space-y-2">
                {brief.faqSection.map((faq, i) => (
                  <div key={i} className="p-3 bg-slate-50 rounded-lg border border-slate-200 text-xs text-slate-800 space-y-1">
                    <div className="font-bold text-indigo-700">Q: {faq.question}</div>
                    <div className="text-[11px] text-slate-500">Targeting query: <code className="bg-white px-1.5 py-0.5 rounded border border-slate-200">{faq.targetKeyword}</code></div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Modal Footer */}
          <div className="p-4 sm:p-6 border-t border-slate-100 flex flex-wrap items-center justify-between gap-3 bg-slate-50/50">
            <button
              onClick={() => setIsGraderOpen(true)}
              className="inline-flex items-center gap-1.5 px-3.5 py-2 text-xs font-bold text-emerald-800 bg-emerald-100 hover:bg-emerald-200 rounded-xl transition-all cursor-pointer shadow-2xs border border-emerald-300/50"
            >
              <Gauge className="w-4 h-4 text-emerald-700" />
              <span>Audit Live URL (SerpDo Grader)</span>
            </button>

            <div className="flex items-center gap-2">
              <button
                onClick={onClose}
                className="px-4 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-200 rounded-lg transition-colors cursor-pointer"
              >
                Close
              </button>
              <button
                onClick={handleCopyMarkdown}
                className="inline-flex items-center gap-2 px-5 py-2 text-xs font-bold text-white bg-slate-900 hover:bg-slate-800 rounded-lg shadow-sm transition-all cursor-pointer"
              >
                {copied ? (
                  <>
                    <Check className="w-4 h-4 text-emerald-400" />
                    <span>Copied to Clipboard!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4" />
                    <span>Copy Markdown Brief</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* 1-Click Page Grader Drawer */}
      <PageGraderDrawer
        targetKeyword={seed}
        isOpen={isGraderOpen}
        onClose={() => setIsGraderOpen(false)}
      />
    </>
  );
};
