'use client';

import React, { useState, useEffect } from 'react';
import { KeywordItem } from '@/lib/autocomplete';
import {
  X,
  Copy,
  Check,
  FileText,
  Sparkles,
  HelpCircle,
  Layers,
  Gauge,
  Loader2,
  Globe,
  BookmarkCheck,
  Flame,
  AlertCircle,
  RefreshCw,
  ExternalLink,
} from 'lucide-react';
import { PageGraderDrawer } from './PageGraderDrawer';
import { ArticleWriterModal } from './ArticleWriterModal';
import { LlmBriefResponse } from '@/lib/llm';
import { SiteContextProfile } from '@/lib/intelligence/site-context';
import { saveSprintItem } from '@/lib/action-cart';

interface ContentBriefModalProps {
  seed: string;
  keywords: KeywordItem[];
  isOpen: boolean;
  onClose: () => void;
  siteUrl?: string;
}

export const ContentBriefModal: React.FC<ContentBriefModalProps> = ({
  seed,
  keywords,
  isOpen,
  onClose,
  siteUrl,
}) => {
  const [copied, setCopied] = useState(false);
  const [savedToSprint, setSavedToSprint] = useState(false);
  const [isGraderOpen, setIsGraderOpen] = useState(false);
  const [isWriterOpen, setIsWriterOpen] = useState(false);
  const [isLoadingLlm, setIsLoadingLlm] = useState(false);
  const [llmData, setLlmData] = useState<LlmBriefResponse | null>(null);
  const [llmError, setLlmError] = useState<string | null>(null);
  const [siteContext, setSiteContext] = useState<SiteContextProfile | null>(null);

  useEffect(() => {
    if (!isOpen || !seed || keywords.length === 0) return;

    let isMounted = true;

    async function loadBrief() {
      setIsLoadingLlm(true);
      setLlmError(null);

      try {
        let loadedContext: SiteContextProfile | null = null;

        if (siteUrl && siteUrl.trim()) {
          try {
            const ctxRes = await fetch('/api/site-context', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ url: siteUrl }),
            });
            const ctxData = await ctxRes.json();
            if (ctxData.success && ctxData.profile && isMounted) {
              loadedContext = ctxData.profile;
              setSiteContext(ctxData.profile);
            }
          } catch {
            // Non-blocking fallback
          }
        }

        const res = await fetch('/api/content-brief', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            seed,
            keywords,
            siteContext: loadedContext
              ? {
                  siteName: loadedContext.siteName,
                  businessType: loadedContext.businessType,
                  targetAudience: loadedContext.targetAudience,
                  situationalSummary: loadedContext.situationalSummary,
                  sampleSitemapUrls: loadedContext.sampleSitemapUrls,
                }
              : undefined,
          }),
        });

        const data = await res.json();
        if (!res.ok || !data.success || !data.llmData) {
          throw new Error(data.error || 'AI content brief synthesis failed. Please check your OpenRouter API key/credits.');
        }

        if (isMounted) {
          setLlmData(data.llmData);
        }
      } catch (err: unknown) {
        if (isMounted) {
          const msg = err instanceof Error ? err.message : 'Failed to generate brief';
          setLlmError(msg);
        }
      } finally {
        if (isMounted) {
          setIsLoadingLlm(false);
        }
      }
    }

    loadBrief();

    return () => {
      isMounted = false;
    };
  }, [isOpen, seed, keywords, siteUrl]);

  if (!isOpen) return null;

  // Primary Focus Keywords (Top 5 genuine search terms)
  const primaryKeywords = keywords.slice(0, 5);

  const h1Title = llmData?.suggestedH1 || `SEO Content Architecture for ${seed}`;
  const h2List = llmData?.recommendedH2s || [];
  const faqList = llmData?.recommendedFaqs || [];

  const markdownContent = `# ${h1Title}

## Target Seed Keyword
- **Seed Keyword:** \`${seed}\`
${siteContext ? `- **Business Context:** ${siteContext.siteName} (${siteContext.businessType}) - ${siteContext.targetAudience}` : ''}
${llmData?.contentAngle ? `- **Content Angle:** ${llmData.contentAngle}\n- **Target Audience:** ${llmData.targetAudience}` : ''}

## Primary Keywords to Include
${primaryKeywords.map((kw) => `- [ ] ${kw.keyword}`).join('\n')}

## Recommended H2 Article Outline
${h2List.map((h2) => `## ${h2}`).join('\n')}

## Recommended FAQs & Schema Ready Answers
${faqList.map((faq) => `### Q: ${faq.question}\n${faq.answerSnippet}`).join('\n\n')}

---
*Generated by Google Keyword Dominator (GKD) with DeepSeek AI & Live Search Grounding*
`;

  const handleCopyMarkdown = async () => {
    await navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSaveToSprint = () => {
    saveSprintItem({
      type: 'content_brief',
      title: `Content Brief: ${seed}`,
      subtitle: `${h1Title} (${h2List.length} H2 sections, ${faqList.length} FAQs)`,
      content: markdownContent,
      metadata: {
        seed,
        h1: h1Title,
      },
    });
    setSavedToSprint(true);
    setTimeout(() => setSavedToSprint(false), 2000);
  };

  return (
    <>
      <div className="fixed inset-0 z-50 bg-slate-950/70 backdrop-blur-xs flex items-center justify-center p-4 overflow-y-auto animate-fadeIn">
        <div className="bg-white rounded-2xl max-w-2xl w-full shadow-2xl border border-slate-200 overflow-hidden flex flex-col max-h-[90vh]">
          {/* Modal Header */}
          <div className="p-4 sm:p-6 border-b border-slate-100 flex items-center justify-between bg-gradient-to-r from-blue-900 via-indigo-900 to-slate-900 text-white">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-blue-500/20 border border-blue-400/30 text-blue-300 rounded-xl shadow-inner">
                <FileText className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-base sm:text-lg font-bold text-white flex items-center gap-2">
                  1-Click AI Content Brief
                  <span className="text-[10px] bg-blue-500 text-white font-extrabold px-2 py-0.5 rounded-full">
                    DeepSeek AI
                  </span>
                </h3>
                <p className="text-xs text-blue-200">
                  Target Seed: <strong className="text-white font-semibold">{seed || 'Seed Topic'}</strong>
                </p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-2 text-slate-400 hover:text-white hover:bg-white/10 rounded-lg transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Modal Body */}
          <div className="p-4 sm:p-6 overflow-y-auto space-y-6 flex-1 text-sm bg-slate-50/50">
            {isLoadingLlm ? (
              <div className="p-12 text-center space-y-3 bg-white rounded-2xl border border-slate-200">
                <Loader2 className="w-8 h-8 animate-spin text-blue-600 mx-auto" />
                <div className="space-y-1">
                  <h4 className="font-extrabold text-sm text-slate-900">
                    Synthesizing Genuine SEO Architecture...
                  </h4>
                  <p className="text-xs text-slate-500 max-w-sm mx-auto">
                    DeepSeek AI is analyzing live Google PAA search results and clustering authentic topical intent for &ldquo;{seed}&rdquo;.
                  </p>
                </div>
              </div>
            ) : llmError ? (
              <div className="p-8 text-center space-y-4 bg-white rounded-2xl border border-rose-200 shadow-2xs">
                <div className="w-12 h-12 rounded-2xl bg-rose-50 text-rose-600 flex items-center justify-center mx-auto">
                  <AlertCircle className="w-6 h-6" />
                </div>
                <div className="space-y-1.5 max-w-md mx-auto">
                  <h4 className="font-black text-sm text-slate-900">
                    Unable to Generate AI Content Brief
                  </h4>
                  <p className="text-xs text-slate-600 leading-relaxed">
                    The AI generation service encountered an error (e.g. OpenRouter API key limit reached or network timeout).
                  </p>
                  <p className="text-[11px] font-mono text-rose-600 bg-rose-50 p-2 rounded-xl border border-rose-100 break-words">
                    {llmError}
                  </p>
                </div>

                <div className="pt-2 flex items-center justify-center gap-3">
                  <button
                    onClick={() => {
                      setLlmError(null);
                      setIsLoadingLlm(true);
                      fetch('/api/content-brief', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({ seed, keywords }),
                      })
                        .then((r) => r.json())
                        .then((d) => {
                          if (d.success && d.llmData) setLlmData(d.llmData);
                          else setLlmError(d.error || 'Failed to generate');
                        })
                        .catch((e) => setLlmError(e.message))
                        .finally(() => setIsLoadingLlm(false));
                    }}
                    className="px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-xs font-bold flex items-center gap-1.5 shadow-sm cursor-pointer transition-colors"
                  >
                    <RefreshCw className="w-3.5 h-3.5" />
                    <span>Try Again</span>
                  </button>
                  <a
                    href="https://openrouter.ai/settings/keys"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl text-xs font-bold flex items-center gap-1.5 transition-colors"
                  >
                    <span>Check OpenRouter Keys</span>
                    <ExternalLink className="w-3.5 h-3.5 text-slate-400" />
                  </a>
                </div>
              </div>
            ) : (
              <>
                {/* Site Context Badge if present */}
                {siteContext && (
                  <div className="p-3 bg-blue-50 border border-blue-200 rounded-xl flex items-center justify-between gap-2 text-xs">
                    <div className="flex items-center gap-2 text-blue-900">
                      <Globe className="w-4 h-4 text-blue-600 shrink-0" />
                      <span>
                        Tailored for <strong className="font-bold">{siteContext.siteName}</strong> ({siteContext.businessType})
                      </span>
                    </div>
                    {siteContext.discoveredUrlsCount > 0 && (
                      <span className="text-[10px] font-mono font-bold bg-white text-blue-700 px-2 py-0.5 rounded border border-blue-200" title="Found in your website sitemap">
                        {siteContext.discoveredUrlsCount} pages in your sitemap
                      </span>
                    )}
                  </div>
                )}

                {/* Suggested Title */}
                <div className="space-y-1.5 p-4 bg-white rounded-xl border border-slate-200 shadow-2xs">
                  <span className="text-xs font-bold uppercase tracking-wider text-blue-700 block flex items-center gap-1">
                    <Sparkles className="w-3.5 h-3.5" />
                    AI-Optimized H1 Title
                  </span>
                  <div className="font-extrabold text-slate-900 text-base">{h1Title}</div>
                  {llmData?.contentAngle && (
                    <p className="text-xs text-slate-500 pt-1">
                      <strong className="text-slate-700">Angle:</strong> {llmData.contentAngle}
                    </p>
                  )}
                </div>

                {/* Core Checklist */}
                <div className="space-y-2">
                  <span className="text-xs font-bold uppercase tracking-wider text-slate-500 block flex items-center gap-1">
                    <Layers className="w-3.5 h-3.5" />
                    Primary Keywords to Include
                  </span>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                    {primaryKeywords.map((kw, i) => (
                      <div key={i} className="flex items-center gap-2 p-2 bg-white rounded-lg border border-slate-200 text-xs font-semibold text-slate-700">
                        <span className="w-2 h-2 rounded-full bg-blue-500 shrink-0" />
                        <span className="truncate">{kw.keyword}</span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* H2 Subheadings */}
                {h2List.length > 0 && (
                  <div className="space-y-2">
                    <span className="text-xs font-bold uppercase tracking-wider text-slate-500 block">
                      Recommended H2 Subheadings &amp; Outline
                    </span>
                    <div className="space-y-1.5">
                      {h2List.map((h2, i) => (
                        <div key={i} className="p-3 bg-white rounded-lg border border-slate-200 text-xs text-slate-900 font-bold">
                          ## {h2}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* FAQ Questions */}
                {faqList.length > 0 && (
                  <div className="space-y-3">
                    <span className="text-xs font-bold uppercase tracking-wider text-slate-500 block flex items-center gap-1">
                      <HelpCircle className="w-3.5 h-3.5" />
                      Recommended FAQs &amp; Schema Ready Answers
                    </span>
                    <div className="space-y-2">
                      {faqList.map((faq, i) => (
                        <div key={i} className="p-3.5 bg-white rounded-xl border border-slate-200 space-y-1.5 text-xs">
                          <div className="font-extrabold text-slate-900 flex items-start gap-1.5">
                            <span className="text-blue-600 font-black">Q:</span>
                            <span>{faq.question}</span>
                          </div>
                          <p className="text-slate-600 pl-4 leading-relaxed text-[11px]">
                            {faq.answerSnippet}
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </>
            )}
          </div>

          {/* Modal Footer */}
          {llmData && !llmError && (
            <div className="p-4 bg-white border-t border-slate-200 flex flex-col sm:flex-row sm:items-center justify-between gap-2">
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setIsWriterOpen(true)}
                  className="px-3.5 py-2 bg-gradient-to-r from-orange-600 to-amber-600 hover:from-orange-700 hover:to-amber-700 text-white rounded-xl text-xs font-black flex items-center gap-1.5 shadow-md transition-all cursor-pointer hover:scale-[1.02]"
                  title="Launch Autonomous Article Factory for this Brief"
                >
                  <Flame className="w-4 h-4 text-amber-200" />
                  <span>Write Full Article</span>
                </button>

                <button
                  onClick={() => setIsGraderOpen(true)}
                  className="px-3 py-2 bg-indigo-50 hover:bg-indigo-100 text-indigo-700 border border-indigo-200 rounded-xl text-xs font-bold flex items-center gap-1.5 transition-colors cursor-pointer"
                >
                  <Gauge className="w-4 h-4 text-indigo-600" />
                  <span>Grade Page</span>
                </button>
              </div>

              <div className="flex items-center gap-2">
                <button
                  onClick={handleSaveToSprint}
                  className="px-3.5 py-2 bg-blue-50 hover:bg-blue-100 text-blue-800 border border-blue-200 rounded-xl text-xs font-bold flex items-center gap-1.5 cursor-pointer transition-colors"
                  title="Pin this brief to your Action Sprint Drawer"
                >
                  {savedToSprint ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <BookmarkCheck className="w-3.5 h-3.5 text-blue-600" />}
                  <span>{savedToSprint ? 'Saved' : 'Save Brief'}</span>
                </button>
                <button
                  onClick={() => {
                    const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8' });
                    const url = URL.createObjectURL(blob);
                    const a = document.createElement('a');
                    a.href = url;
                    a.download = `content-brief-${seed.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.md`;
                    document.body.appendChild(a);
                    a.click();
                    document.body.removeChild(a);
                    URL.revokeObjectURL(url);
                  }}
                  className="px-3 py-2 bg-slate-100 hover:bg-slate-200 text-slate-800 border border-slate-300 rounded-xl text-xs font-bold flex items-center gap-1.5 cursor-pointer transition-colors"
                  title="Download as Markdown file for Notion/Obsidian"
                >
                  <FileText className="w-3.5 h-3.5 text-slate-600" />
                  <span>.md</span>
                </button>
                <button
                  onClick={handleCopyMarkdown}
                  className="px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-xs font-bold flex items-center gap-1.5 shadow-md cursor-pointer transition-colors"
                >
                  {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
                  <span>{copied ? 'Copied' : 'Copy'}</span>
                </button>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* 1-Click Page Grader Drawer */}
      <PageGraderDrawer
        isOpen={isGraderOpen}
        onClose={() => setIsGraderOpen(false)}
        targetKeyword={seed}
      />

      {/* Autonomous Article Writer Modal */}
      <ArticleWriterModal
        seed={seed}
        isOpen={isWriterOpen}
        onClose={() => setIsWriterOpen(false)}
        siteContext={
          siteContext
            ? {
                siteName: siteContext.siteName,
                businessType: siteContext.businessType,
                targetAudience: siteContext.targetAudience,
              }
            : undefined
        }
        suggestedOutline={h2List}
      />
    </>
  );
};
