'use client';

import React, { useState } from 'react';
import { ChevronDown, HelpCircle, ShieldCheck, Database, Search, Target, FileText } from 'lucide-react';

interface FAQItem {
  question: string;
  answer: string;
  icon: React.ReactNode;
}

export const FAQ: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs: FAQItem[] = [
    {
      question: 'What is Google Autocomplete and why is it valuable for SEO?',
      answer:
        'Google Autocomplete is a search feature that predicts what searchers are typing in real time. These suggestions are algorithmically generated by Google based on real search volume, common phrasing, trending queries, and geographical relevance. Tapping into autocomplete gives you instant access to actual user intent and high-converting long-tail keyword variations.',
      icon: <Search className="w-5 h-5 text-blue-600" />,
    },
    {
      question: 'Where does the keyword data in this tool come from?',
      answer:
        'Every single keyword result shown in this tool is retrieved directly from genuine Google completion endpoints. We do NOT fabricate, guess, or simulate keywords using language models or mock data. If Google does not return suggestions for a specific query, we display zero results rather than manufacturing fake data.',
      icon: <Database className="w-5 h-5 text-indigo-600" />,
    },
    {
      question: 'Does this tool display Google monthly search volume?',
      answer:
        'No. Google does not provide exact search volume numbers through public autocomplete endpoints. Tools that display search volume either pay for third-party clickstream data or estimate volume. We provide an honest Relative Score (0–100) based strictly on suggestion ranking order and discovery frequency within your search session, without pretending to be monthly search volume.',
      icon: <ShieldCheck className="w-5 h-5 text-emerald-600" />,
    },
    {
      question: 'How do Wildcard searches work (*)?',
      answer:
        'You can insert an asterisk (*) anywhere in your query (e.g. "best * for small business" or "how to fix * in car"). Google will fill in the blank with popular terms people search for in that middle position. This is one of the most powerful ways to find high-intent niche queries.',
      icon: <Target className="w-5 h-5 text-amber-600" />,
    },
    {
      question: 'What is Alphabet (A-Z) and Question expansion?',
      answer:
        'When enabled, our backend performs sequential queries appending letters (e.g. "keyword a", "keyword b") and question modifiers ("how to keyword", "why keyword"). This simulates an exhaustive manual search across dozens of autocomplete prompts, uncovering comprehensive lists of long-tail terms in seconds.',
      icon: <HelpCircle className="w-5 h-5 text-purple-600" />,
    },
    {
      question: 'Can I export the keyword list to CSV?',
      answer:
        'Yes! You can instantly export all filtered and sorted results as a cleanly formatted CSV file or copy the raw keyword list directly to your clipboard for use in Excel, Google Sheets, or SEO reporting workflows.',
      icon: <FileText className="w-5 h-5 text-rose-600" />,
    },
  ];

  const toggle = (idx: number) => {
    setOpenIndex(openIndex === idx ? null : idx);
  };

  return (
    <div className="w-full max-w-4xl mx-auto py-12 px-4">
      <div className="text-center space-y-2 mb-8">
        <h2 className="text-2xl sm:text-3xl font-extrabold text-slate-900">
          Frequently Asked Questions
        </h2>
        <p className="text-sm text-slate-500 max-w-xl mx-auto">
          Everything you need to know about Google autocomplete keyword research and data transparency.
        </p>
      </div>

      <div className="space-y-3">
        {faqs.map((faq, idx) => {
          const isOpen = openIndex === idx;
          return (
            <div
              key={idx}
              className="bg-white border border-slate-200/80 rounded-xl overflow-hidden transition-all shadow-2xs"
            >
              <button
                onClick={() => toggle(idx)}
                className="w-full text-left p-4 sm:p-5 flex items-center justify-between gap-4 hover:bg-slate-50 transition-colors cursor-pointer"
              >
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-slate-100 rounded-lg shrink-0">
                    {faq.icon}
                  </div>
                  <span className="text-base font-semibold text-slate-800">
                    {faq.question}
                  </span>
                </div>
                <ChevronDown
                  className={`w-5 h-5 text-slate-400 shrink-0 transition-transform duration-200 ${
                    isOpen ? 'rotate-180 text-blue-600' : ''
                  }`}
                />
              </button>
              {isOpen && (
                <div className="px-5 pb-5 pt-1 text-sm text-slate-600 leading-relaxed border-t border-slate-100/60 bg-slate-50/30">
                  {faq.answer}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};
